let _DESCS = {
  'asia-east1':              'Changhua County, Taiwan',
  'asia-east2':              'Hong Kong',
  'asia-northeast1':         'Tokyo, Japan',
  'asia-northeast2':         'Osaka, Japan',
  'asia-northeast3':         'Seoul, South Korea',
  'asia-south1':             'Mumbai, India',
  'asia-southeast1':         'Jurong West, Singapore',
  'australia-southeast1':    'Sydney, Australia',
  'europe-north1':           'Hamina, Finland',
  'europe-west1':            'St. Ghislain, Belgium',
  'europe-west2':            'London, England, UK',
  'europe-west3':            'Frankfurt, Germany',
  'europe-west4':            'Eemshaven, Netherlands',
  'europe-west6':            'Zürich, Switzerland',
  'global':                  'Global HTTP Load Balancer',
  'northamerica-northeast1': 'Montréal, Québec, Canada',
  'southamerica-east1':      'Osasco (São Paulo), Brazil',
  'us-central1':             'Council Bluffs, Iowa, USA',
  'us-east1':                'Moncks Corner, South Carolina, USA',
  'us-east4':                'Ashburn, Northern Virginia, USA',
  'us-west1':                'The Dalles, Oregon, USA',
  'us-west2':                'Los Angeles, California, USA',
  'us-west3':                'Salt Lake City, Utah, USA',
  'us-west4':                'Las Vegas, Nevada, USA',
};
