let _DESCS = {
  'asia-east1':              'Taiwan',
  'asia-east2':              'Hong Kong',
  'asia-northeast1':         'Tokyo',
  'asia-northeast2':         'Osaka',
  'asia-northeast3':         'Seoul',
  'asia-south1':             'Mumbai',
  'asia-southeast1':         'Singapore',
  'asia-southeast2':         'Jakarta',
  'australia-southeast1':    'Sydney',
  'europe-north1':           'Hamina, Finland',
  'europe-west1':            'Belgium',
  'europe-west2':            'London, UK',
  'europe-west3':            'Frankfurt, Germany',
  'europe-west4':            'Netherlands',
  'europe-west6':            'Zurich, Switzerland',
  'global':                  'Global HTTPS Load Balancer',
  'northamerica-northeast1': 'Montreal, Canada',
  'southamerica-east1':      'São Paulo',
  'us-central1':             'Iowa, USA',
  'us-east1':                'South Carolina, USA',
  'us-east4':                'Northern Virginia, USA',
  'us-west1':                'Oregon, USA',
  //'us-west2':                'Los Angeles, USA',
  //'us-west3':                'Salt Lake City, USA',
  //'us-west4':                'Las Vegas, USA',
};
